version: '3.8'

services:
  quantum_app:
    build: .
    container_name: quantum_dev
    volumes:
      - .:/app  # Le code local est synchronis√© dans /app
    working_dir: /app
    # Garde le container actif pour pouvoir s'y connecter
    command: tail -f /dev/null 